name: CI
on: [push, pull_request]
jobs:
  check_format:
    runs-on: ubuntu-latest
    container: { image: "ghcr.io/rollbear/clang:21" }
    name: "check format"
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "check format"
        shell: bash
        run: |
          git config --global --add safe.directory $PWD
          ./check_code_formatting.sh

  build_linux:
    container: { image: "ghcr.io/rollbear/${{matrix.config.container}}" }
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        config:
          - { cxx: clang++-21, stdlib: libc++, container: "clang:21" }
          - { cxx: clang++-21, container: "clang:21" }
          - { cxx: g++-15, container: "gcc:15" }

    name: "Linux ${{matrix.config.cxx}} ${{matrix.config.stdlib}}"
    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: "setup"
        shell: bash
        run: |
          STDLIB=""
          if [ -n "${{matrix.config.stdlib}}" ]
          then
            STDLIB="-stdlib=${{matrix.config.stdlib}}"
          fi
          WARNINGS="-Wall -Wextra -Wconversion -Wpedantic -Werror"
          SANITIZERS="-fsanitize=address,undefined"
          LIBRARY_PREFIX="/usr/local/lib/c++23${{matrix.config.stdlib}}"
          cmake \
            -S . \
            -B build \
            -D unittest=yes \
            -D CMAKE_CXX_STANDARD=23 \
            -D CMAKE_CXX_STANDARD_REQUIRED=yes \
            -D CMAKE_CXX_EXTENSIONS=no \
            -D CMAKE_CXX_COMPILER=${{matrix.config.cxx}} \
            -D CMAKE_CXX_FLAGS="${STDLIB} ${WARNINGS} ${SANITIZERS} --coverage" \
            -D CMAKE_PREFIX_PATH=${LIBRARY_PREFIX} \
            -D CMAKE_VERBOSE_MAKEFILE=yes \
            -D CMAKE_BUILD_TYPE=Debug

      - name: "build"
        run: |
          cmake --build build -t tests/test_composer

      - name: "test"
        run: |
          ./build/tests/test_composer -s

      - name: "collect coverage"
        run: |
          COV=`echo ${{matrix.config.cxx}} | grep -q clang && echo "llvm-cov gcov"|| echo gcov`
          ${COV} -abcfup `find . -name "test*.gcno"`
          ls *.gcov| grep -v 'include#composer'|xargs rm
          find . -name "test*.gcno" | xargs rm

      - name: "upload coverage"
        uses: codecov/codecov-action@v5
        with:
          name: "Linux ${{matrix.config.cxx}} ${{matrix.config.stdlib}}"
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  build_windows:
    runs-on: windows-latest
    name: "Windows MSVC"
    steps:
      - uses: actions/checkout@v4

      - name: Configure MSVC console (Windows)
        uses: ilammy/msvc-dev-cmd@v1

      - name: "setup"
        shell: bash
        run: |
          cmake \
            -S . \
            -B build \
            -D unittest=yes \
            -D CMAKE_CXX_COMPILER=cl \
            -D CMAKE_C_COMPILER=cl \
            -D CMAKE_CXX_STANDARD=23 \
            -D CMAKE_CXX_STANDARD_REQUIRED=yes \
            -D CMAKE_CXX_EXTENSIONS=no \
            -D CMAKE_CXX_FLAGS="'/permissive- /EHsc /W4 /WX'" \
            -D CMAKE_BUILD_TYPE=Debug \
            -D CMAKE_VERBOSE_MAKEFILE=yes \
            -G Ninja

      - name: "build"
        shell: bash
        run: |
          cmake --build build --target test_composer

      - name: "test"
        shell: bash
        run: |
          ./build/tests/test_composer.exe -s
